# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6


# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install

rvm:
 - "1.0.0"

# Commands you want to run that will verify your build.
script:
  - cd ./app/tests && ../../app/vendor/be/bin/codecept  run unit unit

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
